RECALL_VERDICTS = {
    ('adaptativens', 'Subsampling'): ('fp', "Titre 'Adaptive Negative Subsampling' = methode propre extraite ('Adaptive NS'), granularite."),
    ('asa', 'Adversarial Negative Sampling'): ('fp', "Partiel de 'adaptive self-adversarial negative sampling' (methode propre extraite)."),
    ('asa', 'Noise contrastive estimation'): ('miss', "'unified within a sampled noise contrastive estimation framework (Yang et al.)' : approche NS citee, non extraite."),
    ('cake', 'CANS'): ('fp', "Ligne 'TransE+CANS' = 'Commonsense-Aware Negative Sampling' extraite (acronyme vs nom complet)."),
    ('cake', 'NS-KGE'): ('fp', "'None-sampling: NS-KGE (Li et al., 2021)' : concept capture par 'None Sampling' extrait du meme passage."),
    ('cans', 'CKRL (40%)'): ('miss', "Lignes de resultats 'CKRL(LT)'/'CKRL' avec scores : baseline evaluee non extraite (extraits: Bernoulli/Confidence-Aware/Uniform)."),
    ('ccs', 'Dynamic Distribution Sampling'): ('fp', "'divided into... fixed distribution sampling and dynamic distribution sampling' = categorie."),
    ('ccs', 'IGAN'): ('miss', "'IGAN [40] and Kbgan [41] both introduce GAN for negative sampling' : Kbgan extrait mais PAS IGAN."),
    ('conceptdriven', 'CAKE'): ('miss', "'[2] proposes a detachable Commonsense-Aware Knowledge Embedding (CAKE) framework' : framework cite ; CANS extraite mais pas CAKE."),
    ('conceptdriven', 'CANS'): ('fp', "Ligne '+CANS' = 'Commonsense-Aware Negative Sampling' extraite."),
    ('conceptdriven', 'Domain-based Negative Sampling'): ('fp', "'concept domain negative sampling (CDNS)' : 'Concept Domain NS' extraite."),
    ('conceptdriven', 'MVLP'): ('fp', "'multi-view link prediction (MVLP) module' = module de LINK PREDICTION, pas une methode NS."),
    ('dans', 'Adaptive Negative Sampling'): ('fp', "Titre/methode propre 'Diversified and Adaptive NS' extraite (partiel)."),
    ('dans', 'Adversarial Negative Sampling'): ('fp', "Partiel de 'self-adversarial negative sampling' ('Self-adversarial NS' extraite)."),
    ('dans', 'GAN-based Negative Sampling'): ('fp', "'previous GAN-based negative sampling' = categorie (KBGAN/IGAN/HeGAN extraits)."),
    ('dans', 'Importance Sampling'): ('fp', "'learning strategies including GANs, RL, and importance sampling [39]' = categorie de techniques."),
    ('dans', 'SANS'): ('fp', "Ligne 'SANS-RW' : SANS extraite sous 'Structure-Aware Negative Sampling' (variante RW = granularite)."),
    ('dans', 'Self-Adv'): ('fp', "Ligne 'Self-adv' = 'Self-adversarial Negative Sampling' extraite."),
    ('dans', 'Uniform Random Sampling'): ('fp', "'via uniform random sampling' : 'Random Negative Sampling' extraite."),
    ('demix', 'Adversarial Negative Sampling'): ('fp', "Partiel de 'self-adversarial negative sampling' ('Self-adversarial Sampling' extraite)."),
    ('demix', 'CAKE'): ('miss', "'The CANS is a component of CAKE [16]' : CANS extraite mais pas CAKE."),
    ('demix', 'MixGCF'): ('miss', "'MixGCF [13] integrates multiple negative samples...' : mention reelle (MixKG extrait, PAS MixGCF)."),
    ('demix', 'SANS'): ('fp', "Ligne 'TransE+RW-SANS' : 'RW-SANS' extraite."),
    ('demix', 'Self-Adv'): ('fp', "Ligne 'TransE+Self-Adv' = 'Self-adversarial Sampling' extraite."),
    ('demix', 'Commonsense-Aware Negative Sampling'): ('fp', "Ligne 'TransE+CANS' : 'CANS' extraite (nom complet vs acronyme)."),
    ('dhns', 'Self-adversarial Negative Sampling'): ('fp', "Ligne 'SANS' du tableau = la methode SANS extraite ; collision d'acronyme avec Self-adversarial."),
    ('dmns', 'DMNS'): ('fp', "Ligne 'DMNS' = methode propre extraite sous 'Conditional Diffusion-based Multi-level Negative Sampling'."),
    ('dmns', 'Noise contrastive estimation'): ('miss', "'many methods follow the noise contrastive estimation approach [13]' : approche citee, non extraite."),
    ('dmns', 'SANS'): ('miss', "'On graphs, SANS [2] select negative examples from k-hop neighborhoods' : mention reelle, non extraite."),
    ('dns', 'Local-Closed World Assumption Negative Sampling'): ('fp', "Assomption LCWA fondant la corruption aleatoire ; methode operationnelle ('Random NS') extraite."),
    ('eans', 'Adversarial Negative Sampling'): ('fp', "Partiel ('Self-Adversarial NS' extraite)."),
    ('eans', 'EANS'): ('fp', "Ligne 'EANS (ours)' = 'Entity Aware Negative Sampling' extraite."),
    ('eans', 'Random Negative Sampling'): ('fp', "'uniform random negative sampling method' : 'Uniform NS' extraite."),
    ('eans', 'Self-Adv'): ('fp', "Ligne 'Self-adv.(Sun et al.)' = 'Self-Adversarial Negative Sampling' extraite."),
    ('eans', 'Uniform Random Sampling'): ('fp', "'a uniform random sampling method' : 'Uniform NS' extraite."),
    ('eans', 'Structure-Aware Negative Sampling'): ('fp', "Ligne 'SANS + Self-adv.' : 'SANS' extraite (acronyme)."),
    ('erdns', 'Simple Negative Sampling'): ('fp', "'Simple negative sampling methods like uniform sampling' = adjectif."),
    ('erdns', 'Self-adversarial Negative Sampling'): ('fp', "Extraite sous 'Self-Adv' (acronymes [21],[1] du texte)."),
    ('ghn', 'Nearest Neighbor Sampling'): ('fp', "Ablation 'NN' = 'Approximate Nearest Neighbor Negative Sampling' extraite."),
    ('gibbsns', 'Entity Similarity-based Negative Sampling'): ('miss', "'semantic related NS models, such as..., entity similarity-based negative sampling' : methode citee (ESNS, Yao et al.), non extraite."),
    ('gibbsns', 'IGAN'): ('miss', "'IGAN [19] designed a generator and performed advanced negative sampling' : mention reelle, non extraite."),
    ('gibbsns', 'Random Negative Sampling'): ('fp', "'uniform random negative sampling' : 'Uniform Random NS' extraite."),
    ('gibbsns', 'Static Sampling'): ('fp', "'static negative sampling methods' = categorie."),
    ('gibbsns', 'Entity-Aware Negative Sampling'): ('fp', "Ligne 'EANS' : 'EANS' extraite (acronyme) ; le vocab nom-complet collisionne."),
    ('gns', 'Corrupting Positive Instances'): ('fp', 'Description de la meme approche [10] deja comptee via le FN LCWA (pas de double compte).'),
    ('gns', 'Local-Closed World Assumption Negative Sampling'): ('miss', "'a Local-Closed World Assumption (LCWA) approach [10] assumes...' : approche NS citee et discutee, non extraite."),
    ('graphgan', 'IRGAN'): ('miss', "'different with IRGAN (Wang et al. 2017a), the design of graph softmax...' : comparaison reelle, extraits vides."),
    ('hasa', 'Importance Sampling'): ('fp', "'approximated via importance sampling' = technique mathematique de leur derivation."),
    ('htens', 'Dynamic Distribution Sampling'): ('fp', "'dynamic distribution based sampling methods' = categorie."),
    ('kbgan', 'IRGAN'): ('miss', "'IRGAN (Wang et al., 2017) is a recent work which combines...' : related work reel, non extrait."),
    ('las', 'Adaptive Negative Sampling'): ('fp', "'the loss adaptive negative sampling approach' = LAS extraite ('Loss Adaptive Sampling')."),
    ('las', 'Adversarial Negative Sampling'): ('fp', "'LAS is a... adversarial negative sampling approach' = descripteur de LAS extraite ('Loss Adaptive Sampling')."),
    ('las', 'Random Negative Sampling'): ('fp', "'random negative sampling would cause...' : 'Uniform Random NS' extraite."),
    ('las', 'Static Sampling'): ('fp', "'the static negative sampling models, nearest-neighbour and near-miss' = categorie ; les methodes citees sont extraites."),
    ('lemon', 'RW-SANS'): ('fp', "'Uniform RW-SANS [2]' en table de COMPLEXITE ; 'Uniform RW-SANS' extraite."),
    ('lemon', 'SANS'): ('fp', "Table de complexite ; SANS extraite sous 'Structure-aware Negative Sampling'."),
    ('lemon', 'Self-Adv'): ('fp', "'Self-Adv. [15]' en table de complexite (ni resultats ni prose) ; variantes Self-Adv. SANS extraites."),
    ('localcognitive', 'Adversarial Negative Sampling'): ('fp', "Partiel ('Self-adversarial negative sampling' extraite)."),
    ('localcognitive', 'Self-Adv'): ('fp', "Ablation 'w/o self-adv' : 'Self-adversarial negative sampling' extraite."),
    ('m2ixkg', 'Dynamic Negative Sampling'): ('fp', "'fixed negative sampling and dynamic negative sampling' = categorie."),
    ('m2ixkg', 'MixGCF'): ('miss', "'MixGCF [Huang et al., 2021] uses positive mixing and hop mixing' : mention reelle, non extraite."),
    ('m2ixkg', 'Simple Negative Sampling'): ('fp', "'rely on simple negative sampling methods' = adjectif."),
    ('m2ixkg', 'Uniform RW-SANS'): ('fp', "Ligne couverte par 'RW-SANS' extraite (prefixe Uniform = base NS, granularite)."),
    ('m2ixkg', 'Uniform SANS'): ('fp', "Ligne couverte par 'SANS' extraite (granularite)."),
    ('m2ixkg', 'Self-adversarial Negative Sampling'): ('fp', "Collision d'acronyme : 'SANS [Ahrabian]' = Structure-Aware, extraite sous 'SANS'."),
    ('mcns', 'GAN-based Negative Sampling'): ('fp', 'En-tete de categorie ; IRGAN/KBGAN extraits.'),
    ('mcns', 'Importance Sampling'): ('fp', "'FastGCN adopts importance sampling in each layer' = technique GNN, pas une NS de KGE."),
    ('mcns', 'Noise contrastive estimation'): ('miss', "'unified within a Sampled Noise Contrastive Estimation (SampledNCE) framework' : cadre CENTRAL du papier, non extrait."),
    ('mdncaching', 'Dynamic Distribution Sampling'): ('fp', "'MDNCaching is a dynamic distribution-based NS strategy' = descripteur de la methode propre extraite."),
    ('mdncaching', 'Dynamic Negative Sampling'): ('fp', "'the dynamic negative sampling techniques were introduced' = categorie."),
    ('mdncaching', 'GAN-based Negative Sampling'): ('fp', "'GAN based NS strategies IGAN and KBGAN' = categorie ; methodes extraites."),
    ('mdncaching', 'Importance Sampling'): ('fp', "'updating the cache using importance sampling' = composant de NSCaching (extraite)."),
    ('mdncaching', 'MDNCaching'): ('fp', "Ligne 'MDNCaching' = methode propre extraite sous 'Matrix Decomposed Negative Caching'."),
    ('mdncaching', 'SANS'): ('fp', "'SANS [1]' : extraite sous 'Structure Aware Negative Sampling'."),
    ('nmiss', 'Nearest-neighbour Sampling'): ('fp', "'nearest neighbour sampling' : extraite sous 'Nearest Neighbor Sampling' (orthographe)."),
    ('nscaching', 'Cache-based Negative Sampling'): ('fp', "'our cache-based negative sampling scheme' = descripteur de NSCaching (extraite)."),
    ('nscaching', 'Importance Sampling'): ('fp', "'we design importance sampling (IS) strategy to update the cache' = composant de NSCaching (extraite)."),
    ('rcwc', 'Adversarial Negative Sampling'): ('fp', "Partiel ('Self-Adversarial NS' extraite)."),
    ('reasonkge', 'Iterative Negative Sampling'): ('fp', 'Titre de section de LEUR methode (ReasonKGE extraite).'),
    ('reasonkge', 'SANS'): ('fp', "'structure-aware negative sampling (SANS)' : extraite sous le nom complet."),
    ('reasonkge', 'Local-Closed World Assumption Negative Sampling'): ('fp', 'Discussion definitionnelle CWA/LCWA (assomption).'),
    ('sans', 'Adversarial Negative Sampling'): ('fp', "Match partiel dans 'Self-Adversarial negative sampling' ('Self-Adversarial NS' extraite)."),
    ('sans', 'Importance Sampling'): ('fp', "'partition function used in Importance Sampling (Bengio et al. 2003)' = historique NCE en LM."),
    ('sans', 'RW-SANS'): ('fp', "'Uniform RW-SANS (ours)' : extraite sous 'Uniform Random Walk Structure Aware NS'."),
    ('sans', 'SANS'): ('fp', "Extraite sous 'Structure Aware Negative Sampling' (acronyme du tableau)."),
    ('sans', 'Self-Adv'): ('fp', "'Self-Adv. (Sun et al.)' : 'Self-Adversarial Negative Sampling' extraite."),
    ('sans', 'Self-Adv. RW-SANS'): ('fp', "Extraite sous 'Self-Adversarial Random Walk Structure Aware NS'."),
    ('sans', 'Self-Adv. SANS'): ('fp', "Extraite sous 'Self-Adversarial Structure Aware NS'."),
    ('sans', 'Uniform SANS'): ('fp', "Extraite sous 'Uniform Structure Aware NS'."),
    ('selfadv', 'Adversarial Negative Sampling'): ('fp', "Match partiel dans 'self-adversarial negative sampling technique' (extraite)."),
    ('sns', 'Good Negative Sampling'): ('fp', "'still lacks a good negative sampling method' = adjectif anglais."),
    ('sns', 'SANS'): ('fp', "'structure aware negative sampling(SANS)' : extraite sous le nom complet."),
    ('stc', 'Local-Closed World Assumption Negative Sampling'): ('miss', "'we also FOLLOW the LCWA proposed in [Krompass] as a supplementary method' : methode UTILISEE par le papier, non extraite."),
    ('tans', 'Adaptive Negative Sampling'): ('fp', "Partiel de 'Triplet Adaptive Negative Sampling' extraite."),
    ('tans', 'Adversarial Negative Sampling'): ('fp', "Partiel de 'Self-Adversarial Negative Sampling (SANS)' extraite."),
    ('tans', 'SANS'): ('fp', "Colonne 'SANS' = abreviation du papier pour 'Self-Adversarial Negative Sampling' extraite."),
    ('tans', 'Subsampling'): ('fp', "Table analytique ; variantes 'Base/Frequency/Unique-based subsampling' extraites."),
    ('tuckerdncaching', 'Dynamic Distribution Sampling'): ('fp', "'previous dynamic distribution-based NS methods' = categorie."),
    ('tuckerdncaching', 'Dynamic Negative Sampling'): ('fp', "'previous dynamic NS methods IGAN, KBGAN, KSGAN' = categorie (methodes extraites)."),
    ('tuckerdncaching', 'ESNS'): ('fp', "'Entity Similarity-based NS (ESNS)' : extraite sous le nom complet."),
    ('tuckerdncaching', 'SANS'): ('fp', "'Structure Aware Negative Sampling (SANS)' : extraite sous le nom complet."),
    ('tuckerdncaching', 'Self-Adv'): ('fp', "'self-adversarial Self-Adv sampling (RotatE)' : 'Self-Adversarial NS' extraite."),
    ('typeaugmented', 'Adversarial Negative Sampling'): ('fp', "Partiel ('Self-adversarial negative sampling' extraite)."),
    ('sans', 'Uniform RW-SANS'): ('fp', "Figure 2 : extraite sous 'Uniform Random Walk Structure Aware NS'."),
}
